#!/usr/bin/env python

import httplib2, sys

sequence_ids = sys.argv[1]

with open(sequence_ids) as f:
    sequence_ids = f.read().splitlines()
    print sequence_ids

for sequences in sequence_ids:
 
    http = httplib2.Http(".cache")
    server = "http://beta.rest.ensembl.org" 
    ext = "/sequence/id/"+sequences+"?type=cds"
    print ext
    resp, content = http.request(server+ext, method="GET",                  headers={"Content-Type":"text/x-fasta"})
 
    if not resp.status == 200:
        print "Invalid response: ", resp.status
        sys.exit()
 
    print content